const TOGGLE_LEFT_NAV_BAR = 'TOGGLE_LEFT_NAV_BAR';
const OPEN_LEFT_NAV_BAR = 'OPEN_LEFT_NAV_BAR';
const CLOSE_LEFT_NAV_BAR = 'CLOSE_LEFT_NAV_BAR';

export { TOGGLE_LEFT_NAV_BAR, OPEN_LEFT_NAV_BAR, CLOSE_LEFT_NAV_BAR };
